//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMXHTD.Data.DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMXuathangtudong_Entities : DbContext
    {
        public HMXuathangtudong_Entities()
            : base("name=HMXuathangtudong_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDistributor> tblDistributors { get; set; }
        public virtual DbSet<tblRFID> tblRFIDs { get; set; }
        public virtual DbSet<LogStoreOrderOperating> LogStoreOrderOperatings { get; set; }
        public virtual DbSet<tblStoreOrderOperating> tblStoreOrderOperatings { get; set; }
        public virtual DbSet<tblCallVehicleStatu> tblCallVehicleStatus { get; set; }
        public virtual DbSet<tblTrough> tblTroughs { get; set; }
        public virtual DbSet<tblVehicleVoice> tblVehicleVoices { get; set; }
        public virtual DbSet<tblScaleLogOperating> tblScaleLogOperatings { get; set; }
        public virtual DbSet<tblScaleOperating> tblScaleOperatings { get; set; }
        public virtual DbSet<tblStoreOrderOperatingPriority> tblStoreOrderOperatingPriorities { get; set; }
        public virtual DbSet<tblVehicle> tblVehicles { get; set; }
        public virtual DbSet<tblConfigOperating> tblConfigOperatings { get; set; }
        public virtual DbSet<tblTroughOrderOperating> tblTroughOrderOperatings { get; set; }
        public virtual DbSet<tblDeliveryCodeTroughOperating> tblDeliveryCodeTroughOperatings { get; set; }
        public virtual DbSet<tblDeliveryCodeTroughOnDemandOperating> tblDeliveryCodeTroughOnDemandOperatings { get; set; }
        public virtual DbSet<tblDeviceOperating> tblDeviceOperatings { get; set; }
        public virtual DbSet<tblKCSOperating> tblKCSOperatings { get; set; }
    }
}
