//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMXHTD.Data.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCallVehicleStatu
    {
        public int Id { get; set; }
        public int StoreOrderOperatingId { get; set; }
        public int CountTry { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiledOn { get; set; }
        public string LogCall { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string TypeProduct { get; set; }
    }
}
