//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMXHTD.Data.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRFID
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Vehicle { get; set; }
        public Nullable<System.DateTime> DayReleased { get; set; }
        public Nullable<System.DateTime> DayExpired { get; set; }
        public string UserReleased { get; set; }
        public string Note { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<System.DateTime> DayCreate { get; set; }
        public Nullable<System.DateTime> DayUpdate { get; set; }
        public string UserCreate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> LastEnter { get; set; }
    }
}
