//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMXHTD.Data.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScaleLogOperating
    {
        public int Id { get; set; }
        public string Vehicle { get; set; }
        public string DeliveryCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifieldOn { get; set; }
        public Nullable<double> WeightScaleIn { get; set; }
        public Nullable<double> WeightScaleOut { get; set; }
        public Nullable<double> LoadWeightNull { get; set; }
        public Nullable<double> LoadWeightFull { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public Nullable<bool> IsSentScaleIn { get; set; }
        public Nullable<bool> IsSentScaleOut { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDistributeScaleIn { get; set; }
        public Nullable<bool> IsDistributeScaleOut { get; set; }
        public Nullable<System.DateTime> TimeInScale { get; set; }
        public Nullable<System.DateTime> TimeOutScale { get; set; }
    }
}
