//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMXHTD.Data.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScaleOperating
    {
        public int Id { get; set; }
        public string ScaleCode { get; set; }
        public string ScaleName { get; set; }
        public Nullable<bool> IsScaling { get; set; }
        public string Vehicle { get; set; }
        public string DeliveryCode { get; set; }
        public Nullable<bool> ScaleIn { get; set; }
        public Nullable<bool> ScaleOut { get; set; }
        public Nullable<System.DateTime> ModifieldOn { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<bool> TouchSensor { get; set; }
    }
}
